export const conferenceKeys = {
   WESTERN: 'W',
   EASTERN: 'E',
}

export const conferences = {
   E: {
      fullName: 'Eastern Conference',
      shortName: 'East',
      divisions: ['A', 'M'],
   },
   W: {
      fullName: 'Western Conference',
      shortName: 'West',
      divisions: ['C', 'P'],
   },
}

export const divisionKeys = {
   ATLANTIC: 'A',
   CENTRAL: 'C',
   METROPOLITAN: 'M',
   PACIFIC: 'P',
}

export const divisions = {
   A: {
      fullName: 'Atlantic Division',
      shortName: 'Atlantic',
   },
   C: {
      fullName: 'Central Division',
      shortName: 'Central',
   },
   M: {
      fullName: 'Metropolitan Division',
      shortName: 'Metropolitan',
   },
   P: {
      fullName: 'Pacific Division',
      shortName: 'Pacific',
   },
}

export const teamKeys = [
   null,
   'NJD',
   'NYI',
   'NYR',
   'PHI',
   'PIT',
   'BOS',
   'BUF',
   'MTL',
   'OTT',
   'TOR',
   null,
   'CAR',
   'FLA',
   'TBL',
   'WSH',
   'CHI',
   'DET',
   'NSH',
   'STL',
   'CGY',
   'COL',
   'EDM',
   'VAN',
   'ANA',
   'DAL',
   'LAK',
   null,
   'SJS',
   'CBJ',
   'MIN',
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   'WPG',
   'ARI',
   'VGK',
]

export const teams = {
   ANA: {
      fullName: 'Anaheim Ducks',
      locationName: 'Anaheim',
      teamName: 'Ducks',
      abbreviation: 'ANA',
      conference: 'W',
      division: 'P',
   },
   ARI: {
      fullName: 'Arizona Coyotes',
      locationName: 'Arizona',
      teamName: 'Coyotes',
      abbreviation: 'ARI',
      conference: 'W',
      division: 'P',
   },
   BOS: {
      fullName: 'Boston Bruins',
      locationName: 'Boston',
      teamName: 'Bruins',
      abbreviation: 'BOS',
      conference: 'E',
      division: 'A',
   },
   BUF: {
      fullName: 'Buffalo Sabres',
      locationName: 'Buffalo',
      teamName: 'Sabres',
      abbreviation: 'BUF',
      conference: 'E',
      division: 'A',
   },
   CGY: {
      fullName: 'Calgary Flames',
      locationName: 'Calgary',
      teamName: 'Flames',
      abbreviation: 'CGY',
      conference: 'W',
      division: 'P',
   },
   CAR: {
      fullName: 'Carolina Hurricanes',
      locationName: 'Carolina',
      teamName: 'Hurricanes',
      abbreviation: 'CAR',
      conference: 'E',
      division: 'M',
   },
   CHI: {
      fullName: 'Chicago Blackhawks',
      locationName: 'Chicago',
      teamName: 'Blackhawks',
      abbreviation: 'CHI',
      conference: 'W',
      division: 'C',
   },
   COL: {
      fullName: 'Colorado Avalanche',
      locationName: 'Colorado',
      teamName: 'Avalanche',
      abbreviation: 'COL',
      conference: 'W',
      division: 'C',
   },
   CBJ: {
      fullName: 'Columbus Blue Jackets',
      locationName: 'Columbus',
      teamName: 'Blue Jackets',
      abbreviation: 'CBJ',
      conference: 'E',
      division: 'M',
   },
   DAL: {
      fullName: 'Dallas Stars',
      locationName: 'Dallas',
      teamName: 'Stars',
      abbreviation: 'DAL',
      conference: 'W',
      division: 'C',
   },
   DET: {
      fullName: 'Detroit Red Wings',
      locationName: 'Detroit',
      teamName: 'Red Wings',
      abbreviation: 'DET',
      conference: 'E',
      division: 'A',
   },
   EDM: {
      fullName: 'Edmonton Oilers',
      locationName: 'Edmonton',
      teamName: 'Oilers',
      abbreviation: 'EDM',
      conference: 'W',
      division: 'P',
   },
   FLA: {
      fullName: 'Florida Panthers',
      locationName: 'Florida',
      teamName: 'Panthers',
      abbreviation: 'FLA',
      conference: 'E',
      division: 'A',
   },
   LAK: {
      fullName: 'Los Angeles Kings',
      locationName: 'Los Angeles',
      teamName: 'Kings',
      abbreviation: 'LAK',
      conference: 'W',
      division: 'P',
   },
   MIN: {
      fullName: 'Minnesota Wild',
      locationName: 'Minnesota',
      teamName: 'Wild',
      abbreviation: 'MIN',
      conference: 'W',
      division: 'C',
   },
   MTL: {
      fullName: 'Montréal Canadiens',
      locationName: 'Montréal',
      teamName: 'Canadiens',
      abbreviation: 'MTL',
      conference: 'E',
      division: 'A',
   },
   NSH: {
      fullName: 'Nashville Predators',
      locationName: 'Nashville',
      teamName: 'Predators',
      abbreviation: 'NSH',
      conference: 'W',
      division: 'C',
   },
   NJD: {
      fullName: 'New Jersey Devils',
      locationName: 'New Jersey',
      teamName: 'Devils',
      abbreviation: 'NJD',
      conference: 'E',
      division: 'M',
   },
   NYI: {
      fullName: 'New York Islanders',
      locationName: 'New York',
      teamName: 'Islanders',
      abbreviation: 'NYI',
      conference: 'E',
      division: 'M',
   },
   NYR: {
      fullName: 'New York Rangers',
      locationName: 'New York',
      teamName: 'Rangers',
      abbreviation: 'NYR',
      conference: 'E',
      division: 'M',
   },
   OTT: {
      fullName: 'Ottawa Senators',
      locationName: 'Ottawa',
      teamName: 'Senators',
      abbreviation: 'OTT',
      conference: 'E',
      division: 'A',
   },
   PHI: {
      fullName: 'Philadelphia Flyers',
      locationName: 'Philadelphia',
      teamName: 'Flyers',
      abbreviation: 'PHI',
      conference: 'E',
      division: 'M',
   },
   PIT: {
      fullName: 'Pittsburgh Penguins',
      locationName: 'Pittsburgh',
      teamName: 'Penguins',
      abbreviation: 'PIT',
      conference: 'E',
      division: 'M',
   },
   SJS: {
      fullName: 'San Jose Sharks',
      locationName: 'San Jose',
      teamName: 'Sharks',
      abbreviation: 'SJS',
      conference: 'W',
      division: 'P',
   },
   STL: {
      fullName: 'St. Louis Blues',
      locationName: 'St. Louis',
      teamName: 'Blues',
      abbreviation: 'STL',
      conference: 'W',
      division: 'C',
   },
   TBL: {
      fullName: 'Tampa Bay Lightning',
      locationName: 'Tampa Bay',
      teamName: 'Lightning',
      abbreviation: 'TBL',
      conference: 'E',
      division: 'A',
   },
   TOR: {
      fullName: 'Toronto Maple Leafs',
      locationName: 'Toronto',
      teamName: 'Maple Leafs',
      abbreviation: 'TOR',
      conference: 'E',
      division: 'A',
   },
   VAN: {
      fullName: 'Vancouver Canucks',
      locationName: 'Vancouver',
      teamName: 'Canucks',
      abbreviation: 'VAN',
      conference: 'W',
      division: 'P',
   },
   VGK: {
      fullName: 'Vegas Golden Knights',
      locationName: 'Vegas',
      teamName: 'Golden Knights',
      abbreviation: 'VGK',
      conference: 'W',
      division: 'P',
   },
   WSH: {
      fullName: 'Washington Capitals',
      locationName: 'Washington',
      teamName: 'Capitals',
      abbreviation: 'WSH',
      conference: 'E',
      division: 'M',
   },
   WPG: {
      fullName: 'Winnipeg Jets',
      locationName: 'Winnipeg',
      teamName: 'Jets',
      abbreviation: 'WPG',
      conference: 'W',
      division: 'C',
   },
}
