export default {
  BOS: {
    conference: 'E',
    division: 'A',
    seed: 2,
    place: 'Boston',
    name: 'Bruins',
  },
  CGY: {
    conference: 'W',
    division: 'P',
    seed: 1,
    place: 'Calgary',
    name: 'Flames',
  },
  CAR: {
    conference: 'E',
    division: 'M',
    seed: 4,
    place: 'Carolina',
    name: 'Hurricanes',
  },
  COL: {
    conference: 'W',
    division: 'P',
    seed: 4,
    place: 'Colorado',
    name: 'Avalanche',
  },
  CBJ: {
    conference: 'E',
    division: 'A',
    seed: 4,
    place: 'Columbus',
    name: 'Blue Jackets',
  },
  DAL: {
    conference: 'W',
    division: 'C',
    seed: 4,
    place: 'Dallas',
    name: 'Stars',
  },
  NSH: {
    conference: 'W',
    division: 'C',
    seed: 1,
    place: 'Nashville',
    name: 'Predators',
  },
  NYI: {
    conference: 'E',
    division: 'M',
    seed: 2,
    place: 'New York',
    name: 'Islanders',
  },
  PIT: {
    conference: 'E',
    division: 'M',
    seed: 3,
    place: 'Pittsburgh',
    name: 'Penguins',
  },
  SJS: {
    conference: 'W',
    division: 'P',
    seed: 2,
    place: 'San Jose',
    name: 'Sharks',
  },
  STL: {
    conference: 'W',
    division: 'C',
    seed: 3,
    place: 'St. Louis',
    name: 'Blues',
  },
  TBL: {
    conference: 'E',
    division: 'A',
    seed: 1,
    place: 'Tampa Bay',
    name: 'Lightning',
  },
  TOR: {
    conference: 'E',
    division: 'A',
    seed: 3,
    place: 'Toronto',
    name: 'Maple Leafs',
  },
  VGK: {
    conference: 'W',
    division: 'P',
    seed: 3,
    place: 'Vegas',
    name: 'Golden Knights',
  },
  WSH: {
    conference: 'E',
    division: 'M',
    seed: 1,
    place: 'Washington',
    name: 'Capitals',
  },
  WPG: {
    conference: 'W',
    division: 'C',
    seed: 2,
    place: 'Winnipeg',
    name: 'Jets',
  },
}
