export default {
   ANA: {
      conference: 'W',
      division: 'P',
      seed: 2,
      place: 'Anaheim',
      name: 'Ducks',
   },
   BOS: {
      conference: 'E',
      division: 'A',
      seed: 2,
      place: 'Boston',
      name: 'Bruins',
   },
   COL: {
      conference: 'W',
      division: 'C',
      seed: 4,
      place: 'Colorado',
      name: 'Avalanche',
   },
   CBJ: {
      conference: 'E',
      division: 'M',
      seed: 4,
      place: 'Columbus',
      name: 'Blue Jackets',
   },
   LAK: {
      conference: 'W',
      division: 'P',
      seed: 4,
      place: 'Los Angeles',
      name: 'Kings',
   },
   MIN: {
      conference: 'W',
      division: 'C',
      seed: 3,
      place: 'Minnesota',
      name: 'Wild',
   },
   NSH: {
      conference: 'W',
      division: 'C',
      seed: 1,
      place: 'Nashville',
      name: 'Predators',
   },
   NJD: {
      conference: 'E',
      division: 'A',
      seed: 4,
      place: 'New Jersey',
      name: 'Devils',
   },
   PHI: {
      conference: 'E',
      division: 'M',
      seed: 3,
      place: 'Philadelphia',
      name: 'Flyers',
   },
   PIT: {
      conference: 'E',
      division: 'M',
      seed: 2,
      place: 'Pittsburgh',
      name: 'Penguins',
   },
   SJS: {
      conference: 'W',
      division: 'P',
      seed: 3,
      place: 'San Jose',
      name: 'Sharks',
   },
   TBL: {
      conference: 'E',
      division: 'A',
      seed: 1,
      place: 'Tampa Bay',
      name: 'Lightning',
   },
   TOR: {
      conference: 'E',
      division: 'A',
      seed: 3,
      place: 'Toronto',
      name: 'Maple Leafs',
   },
   VGK: {
      conference: 'W',
      division: 'P',
      seed: 1,
      place: 'Vegas',
      name: 'Golden Knights',
   },
   WSH: {
      conference: 'E',
      division: 'M',
      seed: 1,
      place: 'Washington',
      name: 'Capitals',
   },
   WPG: {
      conference: 'W',
      division: 'C',
      seed: 2,
      place: 'Winnipeg',
      name: 'Jets',
   },
};
