export default {
  ARI: {
    conference: 'W',
    division: 'W',
    seed: 7,
    place: 'Arizona',
    name: 'Coyotes',
  },
  BOS: {
    conference: 'E',
    division: 'E',
    seed: 4,
    place: 'Boston',
    name: 'Bruins',
  },
  CGY: {
    conference: 'W',
    division: 'W',
    seed: 6,
    place: 'Calgary',
    name: 'Flames',
  },
  CAR: {
    conference: 'E',
    division: 'E',
    seed: 5,
    place: 'Carolina',
    name: 'Hurricanes',
  },
  CHI: {
    conference: 'W',
    division: 'W',
    seed: 8,
    place: 'Chicago',
    name: 'Blackhawks',
  },
  COL: {
    conference: 'W',
    division: 'W',
    seed: 2,
    place: 'Colorado',
    name: 'Avalanche',
  },
  CBJ: {
    conference: 'E',
    division: 'E',
    seed: 7,
    place: 'Columbus',
    name: 'Blue Jackets',
  },
  DAL: {
    conference: 'W',
    division: 'W',
    seed: 3,
    place: 'Dallas',
    name: 'Stars',
  },
  MTL: {
    conference: 'E',
    division: 'E',
    seed: 8,
    place: 'Montreal',
    name: 'Canadiens',
  },
  NYI: {
    conference: 'E',
    division: 'E',
    seed: 6,
    place: 'New York',
    name: 'Islanders',
  },
  PHI: {
    conference: 'E',
    division: 'E',
    seed: 1,
    place: 'Philadelphia',
    name: 'Flyers,'
  },
  STL: {
    conference: 'W',
    division: 'W',
    seed: 4,
    place: 'St. Louis',
    name: 'Blues',
  },
  TBL: {
    conference: 'E',
    division: 'E',
    seed: 2,
    place: 'Tampa Bay',
    name: 'Lightning',
  },
  VAN: {
    conference: 'W',
    division: 'W',
    seed: 5,
    place: 'Vancouver',
    name: 'Canucks',
  },
  VGK: {
    conference: 'W',
    division: 'W',
    seed: 1,
    place: 'Vegas',
    name: 'Golden Knights',
  },
  WSH: {
    conference: 'E',
    division: 'E',
    seed: 3,
    place: 'Washington',
    name: 'Capitals',
  },
}
