export default {
   ANA: {
      conference: 'W',
      division: 'P',
      seed: 1,
      place: 'Anaheim',
      name: 'Ducks',
   },
   BOS: {
      conference: 'E',
      division: 'A',
      seed: 3,
      place: 'Boston',
      name: 'Bruins',
   },
   CGY: {
      conference: 'W',
      division: 'P',
      seed: 4,
      place: 'Calgary',
      name: 'Flames',
   },
   CHI: {
      conference: 'W',
      division: 'C',
      seed: 1,
      place: 'Chicago',
      name: 'Blackhawks',
   },
   CBJ: {
      conference: 'E',
      division: 'M',
      seed: 3,
      place: 'Columbus',
      name: 'Blue Jackets',
   },
   EDM: {
      conference: 'W',
      division: 'P',
      seed: 2,
      place: 'Edmonton',
      name: 'Oilers',
   },
   MIN: {
      conference: 'W',
      division: 'C',
      seed: 2,
      place: 'Minnesota',
      name: 'Wild',
   },
   MTL: {
      conference: 'E',
      division: 'A',
      seed: 1,
      place: 'Montréal',
      name: 'Canadiens',
   },
   NSH: {
      conference: 'W',
      division: 'C',
      seed: 4,
      place: 'Nashville',
      name: 'Predators',
   },
   NYR: {
      conference: 'E',
      division: 'M',
      seed: 4,
      place: 'New York',
      name: 'Rangers',
   },
   OTT: {
      conference: 'E',
      division: 'A',
      seed: 2,
      place: 'Ottawa',
      name: 'Senators',
   },
   PIT: {
      conference: 'E',
      division: 'M',
      seed: 2,
      place: 'Pittsburgh',
      name: 'Penguins',
   },
   SJS: {
      conference: 'W',
      division: 'P',
      seed: 3,
      place: 'San Jose',
      name: 'Sharks',
   },
   STL: {
      conference: 'W',
      division: 'C',
      seed: 3,
      place: 'St. Louis',
      name: 'Blues',
   },
   TOR: {
      conference: 'E',
      division: 'M',
      seed: 4,
      place: 'Toronto',
      name: 'Maple Leafs',
   },
   WSH: {
      conference: 'E',
      division: 'M',
      seed: 1,
      place: 'Washington',
      name: 'Capitals',
   },
};
